### ISSUE TITLE
Attributes Suggestion

### ISSUE THREAD

**Issue by guerra** [eubr-bigsea/citron#150]

**Comment by ojvictor** [comment]
@michelboaventura there is an implementation of this feature in @waltersf platform. Maybe you can ask him about how he did it. 
http://beta.ctweb.inweb.org.br/publico/citron2/#/workflows/editor/10
I will close the issue for organization purpose.

**Comment by michelboaventura** [comment]
@ojvictor, it is hardcoded on the code, just for demonstration purposes: https://github.com/eubr-bigsea/citron/blob/master/app/components/properties/properties-components.js#L31

**Comment by michelboaventura** [comment]
For each of those operations we must define a function which receives two objects and returns a new one. Something like this:

```Javascript
function(inputs, forms) {
  ...
  return outputs;
}
```
Where ``input`` is an object which has as keys the input ports ids and as attributes an array with the attributes entering the port. Something like this:

```Javascript
{
  inputPort1Id: ["field1", "field2", ..., "fieldn"],
  inputPort2Id: ["fielda", "fieldb", ..., "fieldz"]
}
```
The ``output`` follows the same idea, but using the output ports instead.

The variable ``forms`` is an object representing the state of the operation, using the same notation we send to save a workflow:

```Javascript
{
  "color": {
    "value": "rgb(255, 255, 165)"
  },
  "header": {
    "value": "0"
  },
  "separator": {
    "value": ","
  },
  "infer_schema": {
    "value": "FROM_LIMONERO"
  }
}
```
- [ ] Add Columns
- [ ] Add rows
- [ ] AFT Survival Regression
- [ ] Aggregation
- [ ] ALS Recommender
- [ ] Apply model
- [ ] Area chart
- [ ] Bar chart
- [ ] Broadcast processing data
- [ ] Change attributes
- [ ] Classification model
- [ ] Classification Report
- [ ] Clean missing
- [ ] Clustering model
- [ ] Comment
- [ ] Convert words to vector
- [ ] Correlation
- [ ] Cross validation
- [ ] Data multiplexer
- [ ] Data reader
- [ ] Data reader
- [ ] Data writer
- [ ] Decision tree classifier
- [ ] Difference
- [ ] Evaluate model
- [ ] External input
- [ ] Feature assembler
- [ ] Feature indexer
- [ ] Filter
- [ ] Filter (selection)
- [ ] Frequent itemsets mining
- [ ] Gaussian Mix. Clustering
- [ ] GBT Classifier
- [ ] GBT Regressor
- [ ] Generalized Linear Regressor
- [ ] Generate NGrams
- [ ] Geo Within
- [ ] Graph
- [ ] Index to String
- [ ] Isotonic Regression
- [ ] Join
- [ ] K-Means Clustering
- [ ] LDA Clustering
- [ ] Line chart
- [ ] Linear regression
- [ ] Logistic regression
- [ ] Naive Bayes classifier
- [ ] One Hot Encoder
- [ ] Outlier detection
- [ ] Pearson correlation
- [ ] Perceptron Classifier
- [ ] Pie chart
- [ ] Projection/Select columns
- [ ] Publish as a visualization
- [ ] Random forest classifier
- [ ] Random Forest Regressor
- [ ] Read shapefile
- [ ] Recommendation Model
- [ ] Recurrence
- [ ] Regression Model
- [ ] Remove duplicated rows
- [ ] Remove stop words
- [ ] Replace value
- [ ] Run application
- [ ] Sample
- [ ] Save model
- [ ] Scatter plot
- [ ] Score model
- [ ] Sentiment analysis
- [ ] Service output
- [ ] Set intersection
- [ ] Sort
- [ ] Split
- [ ] Summary Statistics
- [ ] SVM Classification
- [ ] Table visualization
- [ ] Time series
- [ ] Tokenizer
- [ ] Topic report
- [ ] Transformation
- [ ] Word tree
