### ISSUE TITLE
Visualization Metaphors Evaluation

### ISSUE THREAD

**Issue by guerra** [eubr-bigsea/citron#156]

**Comment by gfranciscani** [comment]
Created [Google Drive Folder](https://drive.google.com/drive/folders/0B7jR0vYYlPLcSEdFMXE5OC1ZSXM) to specify used algorithms and related visualizations.

**Comment by gfranciscani** [comment]
The charts below will be implemented at first: 

1. Line Chart
2. Stacked are chart
3. Horizontal bar chart
4. Vertical bar chart
5. Stacked bar chart
6. Grouped bar chart
7. Pie chart
8. Treemap
9. Scatter plot
10. Map (heatmap)
11. Graph (force layout)
12. Box Plot
13. Table
