### ISSUE TITLE
after login, app not redirect

### ISSUE THREAD

**Issue by mgonc** [eubr-bigsea/citron#200]

**Comment by waltersf** [comment]
Solved by PR #233.

**Comment by waltersf** [comment]
No. It is not working. There is a case that fails. If it's the first time I trying to log into the site, it did not redirect. 
How to reproduce:
- Use an incognito window in Chrome. Try to log in using an existing account. App will not redirect.

**Comment by waltersf** [comment]
@mgonc @guerra Reopened.

**Comment by ojvictor** [comment]
When I have created a new user, the "sign up" submit doesn't redirect me to the environment. 
It only redirects me after I click on login submit. 
This is happening on all versions of lemonade (dev, test and demo).
