### ISSUE TITLE
On high latency connections, the interface takes too long to react

### ISSUE THREAD

**Issue by wagnermeirajr** [eubr-bigsea/citron#237]
When using Lemonade in a high latency connection, the user may get lost because the interface takes too long to react. More specifically, when I press execute, it takes about 5 seconds to something to happen in the interface, which refreshes to wait. It may be interesting to perform some local change, display some message or similar, right after the button is pressed, until the actual update comes from the server.

**Comment by waltersf** [comment]
High latency can cause also an error in application and nothing is reported (blank screen). To simulate it, use Chrome Developer Tools, under Network, choose Throttling and something slow (2G, for example).
