### ISSUE TITLE
Box denomination overflows and invades comment box

### ISSUE THREAD

**Issue by wagnermeirajr** [eubr-bigsea/citron#238]
Depending on the length of the box denomination it simply invades the comment box. Check the box "Remover palavras de" in the attached screenshot.
![captura de tela de 2017-05-13 12-44-15](https://cloud.githubusercontent.com/assets/14075212/26026866/2fc6b608-37da-11e7-84a4-4b275c6fc047.png)

**Comment by mgonc** [comment]
fixed on #308
