### ISSUE TITLE
1024x768 (13" Notebook screen) resolution bugs

### ISSUE THREAD

**Issue by ojvictor** [eubr-bigsea/citron#264]
Home
- [x] The visualize column is not aligned 

![workflow_list_arrange](https://cloud.githubusercontent.com/assets/6419508/26585574/e1a9137a-4522-11e7-8bbd-c48678b7fcb5.png)

Workflow
- [x] The horizontal scroll doesn't work properly
- [x] The icons input/output names are overlapping

![workflow_flow_horizontal_scroll_not_working](https://cloud.githubusercontent.com/assets/6419508/26585733/6a731a84-4523-11e7-8684-9aa82755aa6f.png)

Jobs
- [x] If the job's log list is active, the screen doesn't redraw when we use the vertical scroll
- [x] The horizontal scroll doesn't work properly

![jobs_vertical_scroll_resize_error](https://cloud.githubusercontent.com/assets/6419508/26586086/78b3eaf0-4524-11e7-9220-7966fd4b381f.png)

I use the tool [what is my resolution](http://whatismyscreenresolution.net/multi-screen-test) to do the tests.

**Comment by yuricarvalhop** [comment]
@ojvictor  Well, i still didnt implement the If the job's log list is active, the screen doesn't redraw when we use the vertical scroll part of the issue. The problem is, if i make them closer to the element, they are gonna collapse with the sockets, that are located on top of them. Maybe a tooptip would look better? Any other idea?

**Comment by guerra** [comment]
About the port overlapping:
We are considering some changes here. 
First: we remove the these labels and put them on a tooltip.
Second: we add a highlight showing which ports are compatible with the one being dragged
@michelboaventura @waltersf @ojvictor

**Comment by michelboaventura** [comment]
@guerra, I think its the best solution.
