### ISSUE TITLE
Boxes names should have an incremental number when repeated

### ISSUE THREAD

**Issue by guerra** [eubr-bigsea/citron#299]
In order to allow the user to identify each box in the execution log, we should add two new functionalities:

* allow the user to give a name to the box
* In case the user doesn't give a name, we should increment a counter for each repeated name in the current flow.

**Comment by magno-lucas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#299 (in #475)](https://trello.com/c/Un4a4Djv/9-299-in-475)

**Comment by magno-lucas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#299 (in #475)](https://trello.com/c/Un4a4Djv/9-299-in-475)
