### ISSUE TITLE
Table Visualization task result error: The column header is wrong

### ISSUE THREAD

**Issue by ojvictor** [eubr-bigsea/citron#320]
The column attribute doesn't correspond the data column. For example, the header embarked has the attribute data sex, we can see the same with the header class that has the data attribute name. 
Besides, there is a column without header name.

![wrong_column_attributes_header](https://user-images.githubusercontent.com/6419508/27587516-111f5f16-5b1b-11e7-9963-37e0cf9c5914.png)

**Comment by mgonc** [comment]
this problem persist @ojvictor ?

**Comment by ojvictor** [comment]
No. It's working well.
