### ISSUE TITLE
[Task Projection/select columns] saves the same attributes data from two differents boxes

### ISSUE THREAD

**Issue by ojvictor** [eubr-bigsea/citron#321]
I created a *Task Projection/select* box and select the attribute sex from database source
![projection_select_error_01](https://user-images.githubusercontent.com/6419508/27641305-db1ad904-5bf1-11e7-8e87-913c85f0d411.png)

So, I drag a new *Task Projection/select* box and it had the same attribute sex from another box. Look at the new box, it doesnt have any comments but it got from the database the same attribute sex.
![projection_select_error_02](https://user-images.githubusercontent.com/6419508/27641741-24901864-5bf3-11e7-8349-7a17af8b77b6.png)

So, I select another attribute (name) and write a different comment. I dont save the workflow
![projection_select_error_03](https://user-images.githubusercontent.com/6419508/27642019-ed9b09da-5bf3-11e7-95f6-cd6ed43571b1.png)

So the attribute sex selected from the first box changes to the same of the second. 
![projection_select_error_04](https://user-images.githubusercontent.com/6419508/27642102-26b1d122-5bf4-11e7-9f32-ebd6d9ff2506.png)

If I change any attribute item, the two boxes got the same.

**Comment by michelboaventura** [comment]
@ojvictor, did you clicked from one box straight to the other? I think what is happening is the form isn't being updated properly if you don't click on the workflow before changing boxes.

**Comment by ojvictor** [comment]
@michelboaventura I will check your suggestion.
