### ISSUE TITLE
[DEV ENVIRONMENT] The system could force the user to infer the base schema in the loading step

### ISSUE THREAD

**Issue by ojvictor** [eubr-bigsea/citron#342]
If the user creates a workflow with a base without the inferred scheme their modeling will not work properly.

the sample below shows a database sample visualization with and without an inferred schema
![schema_02](https://user-images.githubusercontent.com/6419508/29171488-1bfc2b8e-7db3-11e7-8590-c84de267300d.png)
![schema_01](https://user-images.githubusercontent.com/6419508/29171506-2b0ee896-7db3-11e7-9aed-26a43e1fbef6.png)

**Comment by guerra** [comment]
Discussed this with Matheus and Walter and sometimes the user may not want to use the whole database structure or maybe the file type does not support the "infer schema" function.

**Comment by ojvictor** [comment]
ok! So I will close the issue.
