### ISSUE TITLE
Suggest attributes isn't working to any classification algorithms labels

### ISSUE THREAD

**Issue by ojvictor** [eubr-bigsea/citron#357]
When I insert the value manually the system duplicates it

![algorithm_classifier_error](https://user-images.githubusercontent.com/6419508/29567891-f1cec404-8724-11e7-9c3f-c970c87b253a.png)
![duplicate_problem](https://user-images.githubusercontent.com/6419508/29569191-19d5a612-8729-11e7-84fa-d19bef6f632c.png)

When I remove the box the system launches an exception

![remove_classifier_error](https://user-images.githubusercontent.com/6419508/29568007-5cd07f18-8725-11e7-86cd-acb4a163d64f.png)

**Comment by ojvictor** [comment]
@mgonc not working yet

![suggestion_attributes_form_error01](https://user-images.githubusercontent.com/6419508/29669857-2f4030ce-88bb-11e7-9f78-de84f1eb3481.png)

**Comment by mgonc** [comment]
@waltersf how classifier handles the suggestions attributes?
