### ISSUE TITLE
Ghost boxes when execute workflow

### ISSUE THREAD

**Issue by ojvictor** [eubr-bigsea/citron#359]
This is an intermittent error. 
It occurs after I remove some boxes and executes the workflow.  
![ghost](https://user-images.githubusercontent.com/6419508/29616910-5d9c7fcc-87e9-11e7-9f88-d708d9d6bed9.png)
![ghost02](https://user-images.githubusercontent.com/6419508/29617077-effe1772-87e9-11e7-9cbf-3741b79e958d.png)

**Comment by mgonc** [comment]
I can't reproduce this bug

**Comment by yuricarvalhop** [comment]
@ojvictor Is this still happening? Tried the same workflow used on the screen, couldnt reproduce it either.
