### ISSUE TITLE
Job's Log sample table css error

### ISSUE THREAD

**Issue by ojvictor** [eubr-bigsea/citron#365]
![sample_job_css_table_error](https://user-images.githubusercontent.com/6419508/29666546-1669ce04-88af-11e7-8e6d-493a6127f55f.png)

**Comment by yuricarvalhop** [comment]
We knew about this problem already, thing is, we dont know how we are supposed to make it look good. The tables are just too big for the logs bar, we gotta rethink how this log bar is shown.

**Comment by ojvictor** [comment]
@guerra @waltersf  any suggestion??
