### ISSUE TITLE
The system doesn't save the last boxes from workflow property

### ISSUE THREAD

**Issue by ojvictor** [eubr-bigsea/citron#366]
It is an intermittent error. 
Sometimes when I save any workflow, log out and come back to it, I figure out that the workflow wasn't saved properly.
The last boxes weren't saved properly in the database.
1) I saved my workflow before log out
![saves_error](https://user-images.githubusercontent.com/6419508/29668161-918ef0ea-88b5-11e7-94a7-6d0db478d933.png)
2) I came back to workflow and it wasn't saved properly
![saves_error02](https://user-images.githubusercontent.com/6419508/29668194-aa18c4ba-88b5-11e7-9bbe-26647a3ad783.png)
The system lost the last changes that I have done.
![saves_error03](https://user-images.githubusercontent.com/6419508/29668300-0f7d93d0-88b6-11e7-9787-4b2be5dcd2e2.png)

**Comment by mgonc** [comment]
i can't reproduce this error, same as #359

**Comment by ojvictor** [comment]
@mgonc This error always happens when execution fails in the first attempt.

**Comment by mgonc** [comment]
I aware about this bug and I will discuss the solutions.

**Comment by magno-lucas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#366](https://trello.com/c/5K5iRsf4/1-366)
