### ISSUE TITLE
Service Output Operator ( Saída de serviço)

### ISSUE THREAD

**Issue by ojvictor** [eubr-bigsea/citron#406]
The execute field is empty
![service_exit](https://user-images.githubusercontent.com/6419508/30482433-626afdcc-99f9-11e7-9630-31157b844b24.png)

**Comment by ojvictor** [comment]
![output_service_empty_exec](https://user-images.githubusercontent.com/6419508/30809734-27905908-a1d9-11e7-818a-36c8cc357c4d.png)

**Comment by mgonc** [comment]
@ojvictor what is the problem?
