### ISSUE TITLE
Result does not display the generated code when running workflow first time

### ISSUE THREAD

**Issue by waltersf** [eubr-bigsea/citron#415]
If you run a workflow and right after, in the results screen, click the button "Code", a modal window is displayed, but without any code. If you refresh the same page and click button again, it works.

**Comment by ojvictor** [comment]
@yuricarvalhop still not working

**Comment by yuricarvalhop** [comment]
@ojvictor Its still on Pull request, it worked yesterday, you tried my branch?

**Comment by ojvictor** [comment]
@yuricarvalhop I will wait for the deploy to check the issue.
