### ISSUE TITLE
Editing datasource - Saving

### ISSUE THREAD

**Issue by SergioSJS** [eubr-bigsea/citron#422]
Using chrome.
In Editing datasource screen, when I click in save nothing happens. The changes are saved, but in the console there is an error:

> Error: There is no route named datasources
    at L.handlersFor (vendor-a8f0e950d94adf15a92454fb74b6d010.js:2967)
    at n.applyToState (vendor-a8f0e950d94adf15a92454fb74b6d010.js:3104)
    at E.applyIntent (vendor-a8f0e950d94adf15a92454fb74b6d010.js:3134)
    at y (vendor-a8f0e950d94adf15a92454fb74b6d010.js:2329)
    at o._prepareQueryParams (vendor-a8f0e950d94adf15a92454fb74b6d010.js:2387)
    at o._doTransition (vendor-a8f0e950d94adf15a92454fb74b6d010.js:2383)
    at o.transitionTo (vendor-a8f0e950d94adf15a92454fb74b6d010.js:2364)
    at o.transitionTo (vendor-a8f0e950d94adf15a92454fb74b6d010.js:2287)
    at lemonade-ember-f70c97de76255198e1534382c9359c06.js:315
    at S (vendor-a8f0e950d94adf15a92454fb74b6d010.js:3159)

If I try insert a "Description" of dataset with more then 500 characters the register doesn't saved  and returns another error in the console.

**Comment by quigonjeff** [comment]
I confirm the error.

When saving the file the following error is displayed in the console:

> vendor-a8f0e950d94adf15a92454fb74b6d010.js:1895 Error: There is no route named datasources
>     at L.handlersFor (vendor-a8f0e950d94adf15a92454fb74b6d010.js:2967)
>     at n.applyToState (vendor-a8f0e950d94adf15a92454fb74b6d010.js:3104)
>     at E.applyIntent (vendor-a8f0e950d94adf15a92454fb74b6d010.js:3134)
>     at y (vendor-a8f0e950d94adf15a92454fb74b6d010.js:2329)
>     at o._prepareQueryParams (vendor-a8f0e950d94adf15a92454fb74b6d010.js:2387)
>     at o._doTransition (vendor-a8f0e950d94adf15a92454fb74b6d010.js:2383)
>     at o.transitionTo (vendor-a8f0e950d94adf15a92454fb74b6d010.js:2364)
>     at o.transitionTo (vendor-a8f0e950d94adf15a92454fb74b6d010.js:2287)
>     at lemonade-ember-208155f530b66039b08c02d64f6776c8.js:314
>     at S (vendor-a8f0e950d94adf15a92454fb74b6d010.js:3159)

Web brower: Chromium, Version 60.0.3112.113 (Developer Build) Built on Ubuntu , running on Ubuntu 17.04 (64-bit)

**Comment by mgonc** [comment]
fixed on  #426 
Please check out the application and give us a feedback

**Comment by quigonjeff** [comment]
OK. Edited the description of a datasource; clicked “Save”; no error message in the console; went back to the “Datasources” page. Seems to be working as expected.

**Comment by guerra** [comment]
Closing it for now.
