### ISSUE TITLE
Execute Workflow - Python Error - Frequents itemsets mining

### ISSUE THREAD

**Issue by SergioSJS** [eubr-bigsea/citron#432]
Hi, I found another python error with this configuration:

![error01](https://user-images.githubusercontent.com/2502244/30762536-a5a59628-9fb8-11e7-8024-c74f05dfba99.png)

Executing this workflow the system return the error:

> Traceback (most recent call last): File "/usr/local/juicer/juicer/spark/spark_minion.py", line 306, in _perform_execute self._emit_event(room=job_id, namespace='/stand')) File "/tmp/juicer_app_13_13_189.py", line 210, in main task_futures['2ecfe595-4a4f-425d-9665-4cc91cebc163'].result() File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 405, in result return self.__get_result() File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/thread.py", line 55, in run result = self.fn(*self.args, **self.kwargs) File "/tmp/juicer_app_13_13_189.py", line 209, in <lambda> lambda: frequent_item_set_1(spark_session, cached_state, emit_event)) File "/tmp/juicer_app_13_13_189.py", line 173, in frequent_item_set_1 model = algorithm.fit(out_0) File "/usr/local/spark/python/pyspark/ml/base.py", line 64, in fit return self._fit(dataset) File "/usr/local/spark/python/pyspark/ml/wrapper.py", line 265, in _fit java_model = self._fit_java(dataset) File "/usr/local/spark/python/pyspark/ml/wrapper.py", line 261, in _fit_java self._transfer_params_to_java() File "/usr/local/spark/python/pyspark/ml/wrapper.py", line 124, in _transfer_params_to_java pair = self._make_java_param_pair(param, paramMap[param]) File "/usr/local/spark/python/pyspark/ml/wrapper.py", line 115, in _make_java_param_pair return java_param.w(java_value) File "/usr/local/lib/python2.7/dist-packages/py4j/java_gateway.py", line 1133, in __call__ answer, self.gateway_client, self.target_id, self.name) File "/usr/local/spark/python/pyspark/sql/utils.py", line 79, in deco raise IllegalArgumentException(s.split(': ', 1)[1], stackTrace) IllegalArgumentException: u'FPGrowth_4327be3167f2e758aa42 parameter minSupport given invalid value 5.0.'

**Comment by waltersf** [comment]
Hi,
Min support must be between [0.0, 1.0]. I suggest always start with a support of at least 0.5.

**Comment by SergioSJS** [comment]
Hi!
Ok, I change this.
Now the error changed:

> Traceback (most recent call last): File "/usr/local/juicer/juicer/spark/spark_minion.py", line 306, in _perform_execute self._emit_event(room=job_id, namespace='/stand')) File "/tmp/juicer_app_13_13_206.py", line 210, in main task_futures['2ecfe595-4a4f-425d-9665-4cc91cebc163'].result() File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 405, in result return self.__get_result() File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/thread.py", line 55, in run result = self.fn(*self.args, **self.kwargs) File "/tmp/juicer_app_13_13_206.py", line 209, in <lambda> lambda: frequent_item_set_1(spark_session, cached_state, emit_event)) File "/tmp/juicer_app_13_13_206.py", line 173, in frequent_item_set_1 model = algorithm.fit(out_0) File "/usr/local/spark/python/pyspark/ml/base.py", line 64, in fit return self._fit(dataset) File "/usr/local/spark/python/pyspark/ml/wrapper.py", line 265, in _fit java_model = self._fit_java(dataset) File "/usr/local/spark/python/pyspark/ml/wrapper.py", line 262, in _fit_java return self._java_obj.fit(dataset._jdf) File "/usr/local/lib/python2.7/dist-packages/py4j/java_gateway.py", line 1133, in __call__ answer, self.gateway_client, self.target_id, self.name) File "/usr/local/spark/python/pyspark/sql/utils.py", line 79, in deco raise IllegalArgumentException(s.split(': ', 1)[1], stackTrace) IllegalArgumentException: u'requirement failed: The input column must be ArrayType, but got StringType.'

**Comment by waltersf** [comment]
Sergio,

Felipe will provide a tutorial. The problem in this case is caused by the input. You must split the string containing the features into a vector using a Transformation and a function split. For instance: split('transactions', ' '). In this case, the item delimiter is space, but could be any other.

**Comment by SergioSJS** [comment]
Uhm, ok, thanks! :+1: 

Anyway, maybe it is interesting shows a more friendly massage.

**Comment by magno-lucas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#432](https://trello.com/c/ZGm6g1Wj/2-432)
