### ISSUE TITLE
Can't reset password

### ISSUE THREAD

**Issue by ElaineResende** [eubr-bigsea/citron#434]
When I try to reset my password, I get this error below and nothing else happens.

![image](https://user-images.githubusercontent.com/8547396/30764760-d05c6946-9fc2-11e7-9d8a-eec3625e1043.png)

**Comment by mgonc** [comment]
this feature is passing by test validations and if everything is okay, will be added on next version on wednesday.

**Comment by mgonc** [comment]
@ElaineResende option reset password added in #440 and already deployed. Please report any problems
