### ISSUE TITLE
Reset Password Error

### ISSUE THREAD

**Issue by ojvictor** [eubr-bigsea/citron#439]
When the user enters an email that doesn't exist in the database, the system raises an error (with translate error) and freezes.
The error message remains the same even if the user corrects the email and sends a request. 
He doesn't receive any confirmation about the password reset process.
![reset_password_translate_missing](https://user-images.githubusercontent.com/6419508/30913162-910e1be4-a365-11e7-9802-b4ed382c1ee1.png)

**Comment by ojvictor** [comment]
When the user inserts a correct email and sends a request, the textbox line becomes red. 
It looks like the server is not responding. In this case, the system might display an error message, allowing the user to know that your request cannot be executed.
![reset_password_server_error](https://user-images.githubusercontent.com/6419508/30913793-cdce11a4-a367-11e7-8122-3e564e6ffbb7.png)

**Comment by mgonc** [comment]
fixed on @440

**Comment by ojvictor** [comment]
Its working!! @mgonc 
But you could use the email that the user has already written on the landing page.
When the system redirects the user to request a new password page, the email textbox is empty, forcing the user to rewrite the email.
