### ISSUE TITLE
Opening workflow of other users

### ISSUE THREAD

**Issue by SergioSJS** [eubr-bigsea/citron#449]
If I change the id of the workflow in url I can access workflow of other users.

Example:
https://dm.ctweb.inweb.org.br/home/workflows/**ID**/draw?platform=1

https://dm.ctweb.inweb.org.br/home/workflows/20/draw?platform=1

**Comment by magno-lucas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#449](https://trello.com/c/jS0vvfor/4-449)

**Comment by mgonc** [comment]
Tahiti need to handle this. I am creating there.
