### ISSUE TITLE
The status log of the operation is different from the interface status

### ISSUE THREAD

**Issue by ojvictor** [eubr-bigsea/citron#455]
While the status log of the operation shows the status as "PENDING", the interface shows the result as a "COMPLETED" job.

![screenshot_20171011_100351](https://user-images.githubusercontent.com/6419508/31442586-45188fae-ae6d-11e7-89fd-8298d25b0b79.png)

**Comment by guerra** [comment]
Bug intermitente.

**Comment by magno-lucas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#455](https://trello.com/c/uJ1y9xaE/5-455)

**Comment by mgonc** [comment]
this persists? Many changes was made, can you give more details and jobs which this bugs exists?
