### ISSUE TITLE
I cannot access datasources after remove a database created by data write operation

### ISSUE THREAD

**Issue by ojvictor** [eubr-bigsea/citron#456]
1. Create a workflow that uses "Data Write" Operation and executes it.

![datasource_bug01](https://user-images.githubusercontent.com/6419508/31446822-dc7a807e-ae76-11e7-8b4f-507ecc52741a.png)

2. Access the datasource page and remove the base you created

3. Execute the workflow again.

4. Try to access the datasource page again

![datasource_bug02](https://user-images.githubusercontent.com/6419508/31446850-eb70494c-ae76-11e7-97ce-50c035eb8b03.png)

**Comment by mgonc** [comment]
This error persists?

**Comment by guerra** [comment]
Yes @mgonc it's still hapenning

**Comment by magno-lucas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#456](https://trello.com/c/66ZHxKl0/19-456)
