### ISSUE TITLE
The user cannot change password

### ISSUE THREAD

**Issue by ojvictor** [eubr-bigsea/citron#461]
The change password points to workflows tab.

![change_password_link_error](https://user-images.githubusercontent.com/6419508/31772690-3ca0f660-b4bf-11e7-99b3-0a97a0f763f6.png)

**Comment by magno-lucas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#461 (in #501)](https://trello.com/c/jnA6dgxu/6-461-in-501)
