### ISSUE TITLE
Chart operations aren't working

### ISSUE THREAD

**Issue by ojvictor** [eubr-bigsea/citron#464]
- Some parameters aren't displayed in the execution sidebar
- Suggestion attributes aren't working

@michelboaventura @mgonc 

![chart_error](https://user-images.githubusercontent.com/6419508/31821910-76d1780c-b585-11e7-929d-694c87d5e6a8.png)

**Comment by michelboaventura** [comment]
@ojvictor, I couldn't reproduce this. It is happening all the time?

**Comment by mgonc** [comment]
fixed in #467
