### ISSUE TITLE
Error in my Workflow

### ISSUE THREAD

**Issue by SergioSJS** [eubr-bigsea/citron#468]
I was testing de Aggregation Box and return some erros, after this, my workflow doesn't Execute anymore.

Link to workflow:
https://dm.ctweb.inweb.org.br/home/workflows/90/draw?platform=1

In console, return BAD REQUEST error

**Comment by yuricarvalhop** [comment]
Error was because the job (3131) was still running for some reason

**Comment by mgonc** [comment]
@SergioSJS the problem persists?

**Comment by SergioSJS** [comment]
Nope, everything is ok now. Thanks.
