### ISSUE TITLE
I can't see the result of data writer in page of Datasources

### ISSUE THREAD

**Issue by ThaisMatos** [eubr-bigsea/citron#476]
My workflow is executing correctly(without errors), but the datawriter results don't appears in datasources page. (My console of Chrome is clean, no errors)

![screenshot from 2017-10-28 07-52-55](https://user-images.githubusercontent.com/7713090/32133369-3ded0ef8-bbb5-11e7-83a7-708a8f31595b.png)
![screenshot from 2017-10-28 07-53-32](https://user-images.githubusercontent.com/7713090/32133370-3e102b54-bbb5-11e7-99a8-5f17ce83b928.png)
![screenshot from 2017-10-28 07-54-03](https://user-images.githubusercontent.com/7713090/32133371-3e2e99ea-bbb5-11e7-820c-f7fd7119ee36.png)

**Comment by hofnerw** [comment]
Yes my workflow is also happening the same thing and after running again it returns the message that the file already exists, but it is not visible in the datasources.

**Comment by ThaisMatos** [comment]
Any news about this error?? I need analyse this results to write my conclusions....so, this is delaying my work a lot =/

**Comment by waltersf** [comment]
I fixed the error. Please, comment if the problem persists.

Em 03/11/2017 10:57 PM, "ThaisMatos" <notifications@github.com> escreveu:

**Comment by ThaisMatos** [comment]
Walter...I did execute my workflow again and the file in datasources not was changed. So, I deleted then and I did execute again, and now I can't access my datasources because this error appears:

![screenshot from 2017-11-04 11-25-09](https://user-images.githubusercontent.com/7713090/32405797-1d9279c4-c153-11e7-8063-671ebe4ddf7b.png)

**Comment by ThaisMatos** [comment]
Now, I refreshed the page, clearing the cache, and I can access my datasource now... but the file that I had removed appear again (date is Oct 29, 2017 22:35).

I don't no if the file is new and the date is wrong, or if the file is old. I will make new tests in the end of day, and I can comment after this.
