### ISSUE TITLE
 First flow tasks do not return results

### ISSUE THREAD

**Issue by hofnerw** [eubr-bigsea/citron#478]
When you run the flow for the first time, all tasks are executed and return the result. After adding or not other tasks the hourglass appears but do not return the result. Being difficult to interpret the analysis.

![image](https://user-images.githubusercontent.com/19752743/32144939-e8e9d6ea-bca7-11e7-84d0-0a153abbc0d3.png)

**Comment by magno-lucas** [comment]
@hofnerw  Is this issue still happening? If yes, can you provide more detail in order to reproduce it?

**Comment by magno-lucas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#478](https://trello.com/c/9PKYorJZ/16-478)
