### ISSUE TITLE
Durante todo o dia tem ocorridos erros na execução de task que funcionavam...

### ISSUE THREAD

**Issue by Patrifa** [eubr-bigsea/citron#479]
Durante todo o dia tem ocorrido erros na execução de tasks que funcionavam e isto ocorrem sem eu fazer nenhuma alteração. 

Depois voltam a funcionar do nada.

![image](https://user-images.githubusercontent.com/27018578/32147514-c638e71c-bccf-11e7-8ea6-9159c0837ac2.png)

**Comment by magno-lucas** [comment]
@Patrifa Does this error persist? Are there any specific details or steps to be taken in order to reproduce the issue?

**Comment by magno-lucas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#479](https://trello.com/c/sEUQnGRD/12-479)
