### ISSUE TITLE
"Read shapefile" doesn't delete

### ISSUE THREAD

**Issue by gabrielBarbutti** [eubr-bigsea/citron#488]
Steps to the error 
1) I created a new "Read shapefile" 
2) I opened its attributes 
3) I tried to delete, but was not succeeded 

The console logs are in the below image

![image](https://user-images.githubusercontent.com/18507750/32743916-08ee98ba-c895-11e7-9ec8-a6e6397a2a8f.png)

**Comment by gabrielBarbutti** [comment]
Update: Every time I open the attributes of a "Read shapefile" I can't do the following things:
1) Open the attribute of any other object
2) Add a new object
3) Go to other windows, like home or dashboard

The only thing I was capable to do was loggout.
Everything goes back to normal once I loggout or reload the page

**Comment by mgonc** [comment]
It was a error in database of tahiti. The values_url from its form was wrong. Fixed today.
