### ISSUE TITLE
Error message doesn't appear on job log

### ISSUE THREAD

**Issue by gabrielBarbutti** [eubr-bigsea/citron#492]
When I try to see the error message in the job log it just appear "Canceled by error", so I have to open my browser network log to see it.

![screenshot_20171121_101608](https://user-images.githubusercontent.com/18507750/33072387-7dafbffa-cea6-11e7-8f87-9c81921ddfa8.png)

**Comment by magno-lucas** [comment]
@gabrielBarbutti Is this error still happening? Can you provide more detail in order to reproduce the error?

**Comment by magno-lucas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#492](https://trello.com/c/pTJNMPYv/5-492)

**Comment by gabrielBarbutti** [comment]
It's not happening. I can view the error in the report button
