### ISSUE TITLE
Lemonade doesn't load in my browser anymore

### ISSUE THREAD

**Issue by gabrielBarbutti** [eubr-bigsea/citron#493]
Everytime I try to load Lemonade it gives me a white page. I can only access it in anonymous mode. Also, there are no cookies to clean in regard of Lemonade

![screenshot_20171121_101146](https://user-images.githubusercontent.com/18507750/33072626-73152e3a-cea7-11e7-8f85-53fccd83da9b.png)

**Comment by waltersf** [comment]
There was a problem with proxy server (out of space). 
"When you give a response too big for Nginx (proxy server), it uses the directory /var/cache/nginx  to write as a working directory for temporary files. If the worker process cannot access it, Nginx will terminate the transmission before it completes, thus the error INCOMPLETE_CHUNKED_ENCODING."

May be working now

**Comment by gabrielBarbutti** [comment]
Thank you, now it works
