### ISSUE TITLE
Source code is not retrieved

### ISSUE THREAD

**Issue by wagnermeirajr** [eubr-bigsea/citron#503]
I've used Lemonade in 3 different machines, using Firefox and the source code is not retrieved. I tried F5 and it did not work as well.
![captura de tela de 2017-12-19 18-43-04](https://user-images.githubusercontent.com/14075212/34178122-3af9e48a-e4ed-11e7-9847-8347c60de3f4.png)

**Comment by michelboaventura** [comment]
@wagnermeirajr, could you please press Control + Shift + j and paste any errors logged to the console?

**Comment by michelboaventura** [comment]
Duplicated of #512
