### ISSUE TITLE
Upload database window not centralized

### ISSUE THREAD

**Issue by gpavelar** [eubr-bigsea/citron#506]
And The message of successfully uploaded file doesn't disappear after a long time.

Fig 1.
![upload_database_er1](https://user-images.githubusercontent.com/5896754/35054189-2414761a-fb93-11e7-8e99-bf1d31ed1767.png)

Fig 2. 
![message_appear_but_not_disappear](https://user-images.githubusercontent.com/5896754/35054233-313ac470-fb93-11e7-85b4-54f93a2c8395.png)

**Comment by magno-lucas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#506](https://trello.com/c/CZ1FLY2L/9-506)
