### ISSUE TITLE
I cannot remove the arrow between operations

### ISSUE THREAD

**Issue by ojvictor** [eubr-bigsea/citron#509]
![screenshot_20180123_103823](https://user-images.githubusercontent.com/6419508/35276099-54ba2d4c-0029-11e8-9a8d-813f3fc3c926.png)

**Comment by gpavelar** [comment]
Some operations this action can be performed. But there are many operations that the user cannot remove the arrow between operation, another example:

![bugremovearrowsbetweenoperations](https://user-images.githubusercontent.com/5896754/36557223-73044d30-17e6-11e8-8c1c-78811c0c353e.png)

**Comment by magno-lucas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#509](https://trello.com/c/BIvnTJA9/8-509)
