### ISSUE TITLE
Split operation: Weights percentage error

### ISSUE THREAD

**Issue by ojvictor** [eubr-bigsea/citron#510]
The weights percentage should be 50% -%50%

![screenshot_20180123_105445](https://user-images.githubusercontent.com/6419508/35276778-afbcea8e-002b-11e8-82b7-ad4aec47f496.png)

**Comment by magno-lucas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#510](https://trello.com/c/MUsPgmXp/11-510)
