### ISSUE TITLE
Code generation isn't working

### ISSUE THREAD

**Issue by ojvictor** [eubr-bigsea/citron#512]
![screenshot_20180125_095830](https://user-images.githubusercontent.com/6419508/35387261-179a3cc0-01b6-11e8-8dcc-18449f44797c.png)

**Comment by michelboaventura** [comment]
The problem is that the back-end is taking too long to generate the code, so when we ask for it we get an empty result instead. Since some jobs don't have a code at all we can't distinguish between the two cases. @waltersf what do you think we can do about it?

**Comment by waltersf** [comment]
We can do the following: 
- The show code button will start disabled;
- After the job finishes, we enable the button again;
- If the user clicks the button after this, we retrieve the source code;
- If there is no source code, we display a message to user and ask him if he wants to try again.

**Comment by magno-lucas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#512](https://trello.com/c/Ymgxl3Yk/7-512)
