### ISSUE TITLE
Summary Statistics isn't working

### ISSUE THREAD

**Issue by ojvictor** [eubr-bigsea/citron#513]
I am getting the error below when using summary statistics operation
![image](https://user-images.githubusercontent.com/6419508/35629736-88c5b5da-0686-11e8-947e-33209b176445.png)

![image](https://user-images.githubusercontent.com/6419508/35629806-b7233da8-0686-11e8-86a6-266ea0cacb15.png)

**Comment by mgonc** [comment]
@waltersf seems it's a problem with juicer

**Comment by mgonc** [comment]
I created an issue on Juicer
