### ISSUE TITLE
Can't run 'Filter' operation

### ISSUE THREAD

**Issue by pedrobernardina** [eubr-bigsea/citron#517]
Everytime I try to use the Filter operation (data transformation), I get this error.

![image](https://user-images.githubusercontent.com/15324745/35808905-8bbe82bc-0a6e-11e8-81fc-5e1054f9407e.png)

**Comment by pedrobernardina** [comment]
Workflow:

![image](https://user-images.githubusercontent.com/15324745/35808921-9cf4f7b4-0a6e-11e8-83f8-cd8f9e15cfd6.png)

Filter Function:

![image](https://user-images.githubusercontent.com/15324745/35809030-c461b08a-0a6e-11e8-87f7-01c6dc654c1b.png)

**Comment by mgonc** [comment]
fixed on juicer
