### ISSUE TITLE
Scrollbar in Aggregation operation editor isn't working after add multiples agg functions

### ISSUE THREAD

**Issue by gpavelar** [eubr-bigsea/citron#522]
When you add more functions than the width of the editor screen, the reference from scrollbar is lost. Then, you need to close the window and reopen aggregation function editor to scrollbar works.

Photo 1. Scrollbar works
![photo1](https://user-images.githubusercontent.com/5896754/36065561-cd003c66-0e83-11e8-926b-b40fb6a36e93.jpg)

Photo 2. The scrollbar does not work anymore. 
![photo2](https://user-images.githubusercontent.com/5896754/36065562-cfbab10c-0e83-11e8-9a4c-62242f815dd1.jpg)

Photo 3. Close window and reopen, then scrollbar works.
![photo3](https://user-images.githubusercontent.com/5896754/36065564-d23003d8-0e83-11e8-8f16-f658ae25e6be.jpg)

**Comment by magno-lucas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#522](https://trello.com/c/RJJrKMnM/15-522)

**Comment by magno-lucas** [comment]
The error is still occurring when selecting an attribute in the first column, for example:

The scrollbar works 
![error0](https://user-images.githubusercontent.com/28658618/37794853-8bda35b0-2df1-11e8-8544-a48299e8dc12.png)

When you select from the second column, it still works
![error1](https://user-images.githubusercontent.com/28658618/37794902-aeef676e-2df1-11e8-8ab5-7617dd300877.png)

But when you select from the first, it stops working 
![error2](https://user-images.githubusercontent.com/28658618/37794926-c21d8654-2df1-11e8-9ae5-2c8a957f7959.png)
