### ISSUE TITLE
Optimize Docker container creation

### ISSUE THREAD

**Issue by waltersf** [eubr-bigsea/citron#523]
Docker container creation is taking long. There are some optimizations that can be used in order to avoid all steps.

Please review Dockerfile. Also, if possible, try to reduce the time of building emberjs app.

**Comment by magno-lucas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#523](https://trello.com/c/25fLhOC2/15-523)

**Comment by waltersf** [comment]
Any news?

**Comment by waltersf** [comment]
Some messages:
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 49.66s.

[WARN] (broccoli-uglify-sourcemap) Minifying: `assets/vendor.js` took: 86329ms (more than 20,000ms)

**Comment by mgonc** [comment]
I'm on this task now

**Comment by mgonc** [comment]
Removed gvix in-repo addon
