### ISSUE TITLE
[Usability] Is it possible to have smaller boxes in order to improve layout in large workflows?

### ISSUE THREAD

**Issue by waltersf** [eubr-bigsea/citron#524]
Lemonade Citron is using a relatively large box to represent tasks in workflow. Azure ML Studio does so, but there are many others (e.g. Knime) that use smaller ones. When designing a large workflow, this became an issue. 

Some suggestions:
- Evaluate reducing the width (but there is a problem with ports)
- Remove the ports (but it will not be clear to a user if something is missing or not nor what must be connected). 
- For connections, change their color. Tahiti provides different colors for different port interfaces. It could be used to distinguish crossing connections (if they are connecting ports with different interfaces).
- Reduce the arrow in connection in order to save space. 
- Reduce the size of the border for tasks from 2px to 1px. 
- Instead of having a remove button in each task, allow a user to select a set of tasks and use a delete button in the toolbar.

**Comment by magno-lucas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#524](https://trello.com/c/2GRgLkix/16-524)
