### ISSUE TITLE
In job results, if I click the button "Show code", leave the results and come back again, it shows the source code

### ISSUE THREAD

**Issue by waltersf** [eubr-bigsea/citron#525]
How to reproduce:

- Open a workflow
- Run a job (start the workflow), wait until it finishes
- Click show code
- Go back to the workflow designer
- Run the workflow again
- Before the workflow finishes, as soon it starts, the source code (or empty) is shown.

**Comment by magno-lucas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#525](https://trello.com/c/qfwBZ4Gd/17-525)
