### ISSUE TITLE
Missing function Reference (Transformation Operation)

### ISSUE THREAD

**Issue by gpavelar** [eubr-bigsea/citron#550]
I'm using Transformation Operation
![screenshot_9](https://user-images.githubusercontent.com/5896754/37785887-08e9d7a8-2dda-11e8-8187-f27995797640.png)

The figures below shows 6 kinds of transformation, but at backend there are more than 50 operations (It is not shown).

![screenshot_4](https://user-images.githubusercontent.com/5896754/37785901-111c8cae-2dda-11e8-8a83-c53016655a69.png)
![screenshot_6](https://user-images.githubusercontent.com/5896754/37785902-1141f99e-2dda-11e8-9955-b16927e86e38.png)
![screenshot_7](https://user-images.githubusercontent.com/5896754/37785903-115fcda2-2dda-11e8-9f75-14dd2fd55a33.png)

It's clear that i can construct an expression to transform data, but there is no reference and explanation how to do it. The tab "Syntax" is not correct, because the correct syntax is in lowercase.

I noticed that are missing many transformations and their explanation (input, output, parameters, etc). We need this problem solved to finished the Basic Usage Documentation.

**Comment by mgonc** [comment]
I think this reference needed to be putted on documentation not in form. In my opnion it is better remove all references from this form and the tree generated too. See issue #500
