### ISSUE TITLE
Missing Translation: Sorting

### ISSUE THREAD

**Issue by pedrobernardina** [eubr-bigsea/citron#585]
When we click 'open editor' on the 'sort' operator, sorting methods and references are not translated to Portuguese.

![image](https://user-images.githubusercontent.com/15324745/38617667-fd9d65ec-3d6d-11e8-9499-e32185b8cdcd.png)

![image](https://user-images.githubusercontent.com/15324745/38617685-09fd6c2e-3d6e-11e8-80ee-5bbc1dc40acb.png)

**Comment by mgonc** [comment]
I will create in tahiti repo.
