### ISSUE TITLE
When saving a workflow, all data associated to tasks is being sent back again

### ISSUE THREAD

**Issue by waltersf** [eubr-bigsea/citron#591]
Task is send all related entities back to Tahiti: uiPorts, operations, etc. This is causing an error in back-end (413 Request Entity too Large) because the size of the POST data is bigger than 2M. 

As temporary solution, I'm increase the limit to 5M, but it needs to be fixed in Citron, otherwise, very large workflows will fail to be saved.

**Comment by gpavelar** [comment]
![bug-people spath](https://user-images.githubusercontent.com/5896754/38848700-cc189364-41de-11e8-95a8-602031cd1834.jpg)
