### ISSUE TITLE
Cannot update workflow

### ISSUE THREAD

**Issue by pedrobernardina** [eubr-bigsea/citron#628]
On localhost, whenever I edit a workflow and run it, it resets.

![image](https://user-images.githubusercontent.com/15324745/42649880-4a57b8fe-85e1-11e8-823a-bbb942f295b1.png)
On this figure, no parameter is found from the datareader. Then I save (or run) the workflow:

![image](https://user-images.githubusercontent.com/15324745/42649929-68d824c6-85e1-11e8-98d3-1a9d6920e476.png)
The boxes are never connected. It seems to be a caching problem.

**Comment by mgonc** [comment]
I could not reproduce this. Need more information
