### ISSUE TITLE
Problema ao se tentar inferir o tipo da base de dados

### ISSUE THREAD

**Issue by paulohdscoelho** [eubr-bigsea/citron#646]
Ao clicar no botão infer schema, o seguinte erro aparece:

![image](https://user-images.githubusercontent.com/17729984/45912418-465ef480-bdf7-11e8-98b1-2fc4b96a7d41.png)

**Comment by gpavelar** [comment]
Teste alterar de "utf-8" para "latin-1" ou simplesmente deixe a opção de formatação em branco.

**Comment by paulohdscoelho** [comment]
Troquei pra latin-1 e está dando exatamente o mesmo erro

**Comment by gpavelar** [comment]
O mesmo acontece quando você deixa a opção de formatação em branco?

**Comment by paulohdscoelho** [comment]
Sim. Descobri que o erro estava na minha base, que continha um caractere de espaço parseável apenas em Latin-3.
